### Daily Challenge 

In [7]:
import numpy as np

## 1

In [2]:
data = np.array(np.random.randint(1, 100, size=25)).reshape(5, 5)
print("Original Data:")
print(data)

data[1], data[3] = data[3].copy(), data[1].copy()

print("\nData with Swapped Rows:")
print(data)

Original Data:
[[80 71 15 28 28]
 [89 38 23 93  6]
 [59 30 95 93  5]
 [60 67 64 16  9]
 [45 14 79 33 10]]

Data with Swapped Rows:
[[80 71 15 28 28]
 [60 67 64 16  9]
 [59 30 95 93  5]
 [89 38 23 93  6]
 [45 14 79 33 10]]


## 2

In [5]:
data = np.array(np.random.randint(1, 100, size=25)).reshape(5, 5)
print("Original Data:")
print(data)

min_val = np.min(data)
max_val = np.max(data)
normalized_data = (data - min_val) / (max_val - min_val)

print("\nNormalized Data:")
print(normalized_data)

Original Data:
[[ 2 89 27 91 25]
 [91  5 75 75 25]
 [55 42 85 57 47]
 [88 90 19 65  5]
 [38 68 87 96 60]]

Normalized Data:
[[0.         0.92553191 0.26595745 0.94680851 0.24468085]
 [0.94680851 0.03191489 0.77659574 0.77659574 0.24468085]
 [0.56382979 0.42553191 0.88297872 0.58510638 0.4787234 ]
 [0.91489362 0.93617021 0.18085106 0.67021277 0.03191489]
 [0.38297872 0.70212766 0.90425532 1.         0.61702128]]


## 3

In [6]:
data = np.array(np.random.randint(1, 100, size=25)).reshape(5, 5)
print("Original Data:")
print(data)

mean_val = np.mean(data)
std_val = np.std(data)

z_score_data = (data - mean_val) / std_val

print("\nZ-score Normalized Data:")
print(z_score_data)

Original Data:
[[42  5 46 11 49]
 [18 15 28 30 25]
 [62 95  3 59  5]
 [95 69 37 59 43]
 [30 92 15 93 10]]

Z-score Normalized Data:
[[ 0.01906918 -1.24085885  0.15527762 -1.0365462   0.25743394]
 [-0.79818143 -0.90033776 -0.45766034 -0.38955613 -0.55981667]
 [ 0.70011136  1.82383096 -1.30896307  0.59795503 -1.24085885]
 [ 1.82383096  0.93847612 -0.15119136  0.59795503  0.05312129]
 [-0.38955613  1.72167463 -0.90033776  1.75572674 -1.07059831]]


## 4

In [8]:
data = np.array(np.random.randint(1, 100, size=25)).reshape(5, 5)
print("Original Data:")
print(data)

flattened_data = np.ravel(data)

num_subarrays = 5
sub_arrays = np.split(flattened_data, num_subarrays)

print("\nSub-arrays:")
for sub_array in sub_arrays:
    print(sub_array)

Original Data:
[[85 49 30 10 44]
 [79 60 41 60 27]
 [82 91 42 11  7]
 [68 19 32  8 54]
 [ 7 66 29 48 27]]

Sub-arrays:
[85 49 30 10 44]
[79 60 41 60 27]
[82 91 42 11  7]
[68 19 32  8 54]
[ 7 66 29 48 27]


## 5

In [9]:
vector1 = np.array([3, 5, 6, 7, 8])
vector2 = np.array([2, 4, 6, 8, 10])

dot_product = np.dot(vector1, vector2)

print("Dot Product:", dot_product)

Dot Product: 198


## 6

In [10]:
data = np.array(np.random.randint(1, 100, size=25)).reshape(5, 5)
data2 = np.array(np.random.randint(1, 100, size=9)).reshape(3, 3)

matrix_product = np.dot(data[:3, :3], data2)

print("Matrix Product:")
print(matrix_product)

Matrix Product:
[[9706 7648 7466]
 [7934 5691 4144]
 [6420 6839 8817]]


## 7

In [12]:
identity_matrix = np.identity(3)
scaled_matrix = 2 * identity_matrix
inverse_matrix = np.linalg.inv(scaled_matrix)

print("Inverse Matrix:")
print(inverse_matrix)

Inverse Matrix:
[[0.5 0.  0. ]
 [0.  0.5 0. ]
 [0.  0.  0.5]]


## 8

In [14]:
data = np.array(np.random.randint(1, 100, size=25)).reshape(5, 5)
data_3x3 = data[:3, :3]

eigenvalues, eigenvectors = np.linalg.eig(data_3x3)

print("Eigenvalues:", eigenvalues)
print("Eigenvectors:", eigenvectors)

Eigenvalues: [184.49690886 -20.32152669   5.82461783]
Eigenvectors: [[-0.62835358 -0.70401395  0.04072284]
 [-0.45836131  0.68607482 -0.32165533]
 [-0.62855125  0.18348215  0.94598071]]


## 9

In [18]:
data = np.array(np.random.randint(1, 100, size=25)).reshape(5, 5)
indices = np.random.choice(data.size, 5, replace=False)
data_flattened = data.flatten().astype(float)
data_flattened[indices] = np.nan

missing_indices = np.where(np.isnan(data_flattened))
print(missing_indices)

(array([ 1,  3,  7, 22, 24], dtype=int64),)


## 10

In [19]:
data = np.array(np.random.randint(1, 100, size=25)).reshape(5, 5)
indices = np.random.choice(data.size, 5, replace=False)
data_flattened = data.flatten().astype(float)
data_flattened[indices] = np.nan

missing_indices = np.where(np.isnan(data_flattened))

mean_value = np.nanmean(data_flattened)
data_flattened[missing_indices] = mean_value

data_filled = data_flattened.reshape(5, 5)
print(data_filled)

[[98.  51.7 55.  34.  58. ]
 [60.   1.  51.7 51.7 19. ]
 [68.  24.  45.   7.  26. ]
 [51.7 93.  66.  14.  77. ]
 [93.  78.  65.  53.  51.7]]
