EX XP

1)

In [2]:
import numpy as np

2.

In [6]:
vector = np.zeros(10)
vector

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

3)

In [3]:
array = np.zeros(10, dtype=np.float64)

memory_size = array.size * array.itemsize

print(memory_size)


80


4.

In [9]:
help(np.add)

Help on ufunc:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])
    
    Add arguments element-wise.
    
    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array wi

5.

In [10]:
vector = np.arange(10, 50)
print(vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


6.

In [11]:
vector = np.arange(10, 50)
reversed_vector = vector[::-1]
print(reversed_vector)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


7.

In [12]:
values = np.arange(9)
matrix = np.reshape(values, (3, 3))
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


8.

In [16]:
array = np.array([1, 2, 0, 0, 4, 0])
non_zero_indices = np.nonzero(array)
print(non_zero_indices)


(array([0, 1, 4], dtype=int64),)


9.

In [17]:
identity_matrix = np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


10.

In [18]:
row_values = np.arange(5)
matrix = np.tile(row_values, (5, 1))
print(matrix)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


11.

In [20]:
vector = np.linspace(0.09090909, 0.90909091, 10)
print(vector)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


12.

In [21]:
random_vector = np.random.rand(10)
sorted_vector = np.sort(random_vector)
print(sorted_vector)

[0.21059648 0.21447724 0.23158824 0.23977864 0.26951839 0.4636147
 0.51073931 0.59299558 0.68744293 0.84554648]


13.

In [22]:
int_types = [np.int8, np.int32, np.int64]
for int_type in int_types:
    info = np.iinfo(int_type)
    print(f"Integer type: {int_type.__name__}")
    print(f"Minimum value: {info.min}")
    print(f"Maximum value: {info.max}")
    print()

float_types = [np.float32, np.float64]
for float_type in float_types:
    info = np.finfo(float_type)
    print(f"Floating-point type: {float_type.__name__}")
    print(f"Minimum value: {info.min}")
    print(f"Maximum value: {info.max}")
    print()

Integer type: int8
Minimum value: -128
Maximum value: 127

Integer type: int32
Minimum value: -2147483648
Maximum value: 2147483647

Integer type: int64
Minimum value: -9223372036854775808
Maximum value: 9223372036854775807

Floating-point type: float32
Minimum value: -3.4028234663852886e+38
Maximum value: 3.4028234663852886e+38

Floating-point type: float64
Minimum value: -1.7976931348623157e+308
Maximum value: 1.7976931348623157e+308



14.

In [23]:
float_array = np.array([1.5, 2.7, 3.3, 4.8], dtype=np.float32)
print("Float array:")
print(float_array)

float_array = float_array.astype(np.int32)
print("\nInteger array:")
print(float_array)

Float array:
[1.5 2.7 3.3 4.8]

Integer array:
[1 2 3 4]


15.

In [25]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]], dtype=np.int32)

row_means = np.mean(matrix, axis=1)

print("Original matrix:")
print(matrix)

row_means_int32 = row_means.astype(np.int32)

matrix -= row_means_int32.reshape(-1, 1)

print("\nMatrix after subtracting row means:")
print(matrix)

Original matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Matrix after subtracting row means:
[[-1  0  1]
 [-1  0  1]
 [-1  0  1]]


16.

In [26]:
array = np.array([[3, 2, 1],
                  [6, 5, 4],
                  [9, 8, 7]])

n = 1

indices = np.argsort(array[:, n])

sorted_array = array[indices]

print("Original array:")
print(array)

print("\nSorted array by the nth column:")
print(sorted_array)

Original array:
[[3 2 1]
 [6 5 4]
 [9 8 7]]

Sorted array by the nth column:
[[3 2 1]
 [6 5 4]
 [9 8 7]]


17.

In [28]:
array = np.array([[0, 1, 2],
                  [3, 4, 5],
                  [6, 7, 8]])

row1 = 0
row2 = 1

array[row1], array[row2] = array[row2].copy(), array[row1].copy()

print("\nArray after swapping rows:")
print(array)


Array after swapping rows:
[[3 4 5]
 [0 1 2]
 [6 7 8]]


18.

In [30]:
C = np.array([0, 2, 3, 1, 0, 0, 2])

A = np.repeat(np.arange(len(C)), C)

print("Original bincount array:")
print(C)

print("\nGenerated array A:")
print(A)

print("\nnp.bincount(A):")
print(np.bincount(A))

Original bincount array:
[0 2 3 1 0 0 2]

Generated array A:
[1 1 2 2 2 3 6 6]

np.bincount(A):
[0 2 3 1 0 0 2]
